services:
  service-java:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-java
    volumes:
      - /home/deploy/configServiceJava/application.properties:/app/config/application.properties:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_LOCATION=file:/app/config/application.properties
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - paradox-network

networks:
  paradox-network:
    name: paradox_paradox-network
    external: true
